name: Deploy to S3

on:
  push:
    tags:
      - 'v*'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Retype Build
        run: npx retype build --output dist --key "${{ vars.RETYPE_LICENSE_KEY || secrets.RETYPE_LICENSE_KEY }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy static site to S3 bucket
        run: |
          aws s3 sync dist s3://cms-documentation \
            --delete \
            --acl public-read \
            --cache-control "max-age=0,no-cache,no-store,must-revalidate"